### ISSUE TITLE
Polymorphic Tags

### ISSUE THREAD

**Issue by amadden80** [Holderness/Canadian-Tuxedo#1]
Looks like your tags could have used some polymorphic relationships.  Take at look at this documentation.  What do you think?

http://guides.rubyonrails.org/association_basics.html#polymorphic-associations

**Comment by deniseb89** [comment]
I was thinking we could implement this after I heard the ProjectShare group talking about it.

**Comment by amadden80** [comment]
Makes sense.  Sure!  :)
